name: blood_donation
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.11+2
  google_maps_flutter: ^0.5.30
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova-Regular.ttf
        - asset: fonts/ProximaNova-Thin.ttf
        - asset: fonts/ProximaNova-Extrabold.ttf
        - asset: fonts/ProximaNova-Bold.ttf
        - asset: fonts/ProximaNova-Black.ttf
        - asset: fonts/ProximaNova-Alt-Thin.ttf
        - asset: fonts/ProximaNova-Alt-Light.ttf
        - asset: fonts/ProximaNova-Alt-Bold.ttf
    - family: HarfFannan
      fonts:
        - asset: fonts/Harf-Fannan.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
